# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LastFM Companion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LastFM Companion
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'

  target 'LastFM CompanionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LastFM CompanionUITests' do
    # Pods for testing
  end

end
